### ISSUE TITLE
测试代码的疑问

### ISSUE THREAD

**Issue by CircccleK** [fengzhang427/LRD#10]
![image](https://github.com/fengzhang427/LRD/assets/78095525/b002a389-a96c-4f72-8190-3968cbaca353)
想请教下测试LRD数据集时，为什么在raw2rgb前要对noisy_image * ratio？

**Comment by fengzhang427** [comment]
因为LRD数据集是在-EV/-2EV/-3EV这样的暗光环境下拍摄的RAW，这个ratio是一个Amplification Ratio，相当于把RAW图的亮度拉到与GT的RAW图一致（拉高亮度也同时会增大噪声）。
