### ISSUE TITLE
Can you please provide another dataset download link?

### ISSUE THREAD

**Issue by dgjung0220** [fengzhang427/LRD#2]
Hi, Thank you for your research work.
By the way, can you provide another dataset download link?
Baidu program is hard to use another country...

**Comment by fengzhang427** [comment]
The dataset cannot be uploaded to google drive since it only provides 15GB of storage space. Otherwise, since China restricts the purchase of upgraded google drive storage space, we are sorry that we cannot provide another dataset download link, or do you have any other suitable suggestions?

**Comment by fengzhang427** [comment]
> Hi, Thank you for your research work. By the way, can you provide another dataset download link? Baidu program is hard to use another country...

The dataset cannot be uploaded to google drive since it only provides 15GB of storage space. Otherwise, since China restricts the purchase of upgraded google drive storage space, we are sorry that we cannot provide another dataset download link, or do you have any other suitable suggestions?

**Comment by dgjung0220** [comment]
Thank you for the response. I've heard, and it seems like there's no specific alternative. I'll give Baidu Network's Chinese language a try...lol :)

**Comment by fengzhang427** [comment]
I have created a Dropbox download link https://www.dropbox.com/scl/fi/tari9hvf2ubxo232owekz/LRD.zip?rlkey=7zj9kqgsf06g97smexkrzv05q&dl=0, you can try this.

**Comment by dgjung0220** [comment]
Cool. Downloaded well. thxs.

**Comment by alvlar02** [comment]
Can you provide another dataset download link again?
Baidu program is hard to use another country...
