### ISSUE TITLE
Rawpy versions the experiments use

### ISSUE THREAD

**Issue by Rishit-dagli** [fengzhang427/LRD#4]
I was wondering if there is a specific version of Rawpy you use:

```
AttributeError: 'rawpy._rawpy.RawPy' object has no attribute 'rgb_camera_matrix'
```

**Comment by fengzhang427** [comment]
Sorry for the mistake, our rawpy version references the ELD to provide the color_matrix, the rawpy version can be found https://github.com/Vandermode/ELD.
