### ISSUE TITLE
新相机的noise porfile 如何获取？

### ISSUE THREAD

**Issue by quhaoooo** [fengzhang427/LRD#5]
大佬，您好。拜读您的文章，看到有一句话如下？ 想请问您如果我有一个相机，我用什么exiftool来获取相应的noise profile呢？ 
![image](https://github.com/fengzhang427/LRD/assets/99603607/549db24a-5766-4386-aef5-ad01c4f2de1f)

**Comment by fengzhang427** [comment]
直接用ExifTool这个工具就可以读到DNG图像里面的参数，如下图所示：
<img width="323" alt="image" src="https://github.com/fengzhang427/LRD/assets/67069761/22ec0c00-0033-4649-aa09-92f8a74ec5db">
但是好像不是每个厂家都会把in-camera的noise profile放出来，所有部分相机拍出来的RAW图可能读不出来这个数据，那就需要比较专业的方法去标定了，但是这个标定过程比较简单，我们只需要标定信号相关部分的噪声即可。

**Comment by quhaoooo** [comment]
好的，感谢大佬。 另外咨询一下以上两个参数分别代表着什么呢？

**Comment by fengzhang427** [comment]
这两个参数的叫法挺多的，我一般叫作shot-noise的参数和read-noise的参数，然后shot-noise是用于泊松分布的参数，read-noise是用于高斯分布的参数，这个具体的你可以参考ELD这篇文章，然后代码可以参考我在noise_profile里面放的py文件。

**Comment by quhaoooo** [comment]
感谢大佬。

**Comment by quhaoooo** [comment]
大佬我后面看了一些论文，您展示的DNG图像里0.004是shot noise 中的 lamda, 0是read noise中高斯分布的sigma ？ 这里展示是0表明是没做校正？
另外我看您的代码里的Py文件，没有校正的代码只有一些已经校正好的参数，是这样吗？
