### ISSUE TITLE
Question about the pre-trained denoiser

### ISSUE THREAD

**Issue by suiyoubi** [fengzhang427/LRD#8]
Hi! I'd like to get more details about the pre-trained denoise-net. Is the pre-trained denoise-net trained using the same model architecture and hyperparameters as the downstream-task denoiser, and only the dataset is different (as explained in [issue 3](https://github.com/fengzhang427/LRD/issues/3)? Specifically, does the pre-trained denoiser have the following training setting:
• Batch size = 1
• Patch size = 512x512
• Initial lr = 2 * 10^-4
• Milestones at 100, 180
• # of epochs = 200
• Model architecture: UNetSeeInDark
• For the SID Sony dataset, trained and validated on: Sony_train_list.txt, Sony_val_list.txt
Please correct me if I'm wrong. Thank you very much!

**Comment by fengzhang427** [comment]
Sorry for the late reply. 
That's correct. We utilize the same training setting.
