### ISSUE TITLE
reimplement problem of Fourier Transformer Discriminator

### ISSUE THREAD

**Issue by kaiq663** [fengzhang427/LRD#9]
1，As shown in Table 1 of your suuplement, patch size decreases(16->8->4).But in the Figure3. of your paper, patch size increase instead(x2 x2).Quite confusing, which?

2, Instead of NCHW format in  CV, NLP takes [batch, sequence lengh, embedding]. 

Taking [128,4,64,64] as an example, it will go through patch process like below, 
[128,4,64,64] ->  [128,4,4,16,4,16] -> [128,64,256(16x16)][B, C, HW] in which 16 is the patch size shown in your Table 1.
[128,4,64,64] -> [128,4,8,8,8,8] -> [12,256,64(8x8)] -> in which 8 is the patch size shown in your Table 1.
[128,4,64,64] -> [128,4,16,4,16,4] ->[12,1024,16(4x4)] ->  in which 4 is the patch size shown in your Table 1.

I think 256(16*16) in  [128,64,256][B, C, HW]   which means all pixel in a single channel patch is the embdding we want.Why do you take 64 as embedding and 256 as sequence length[128, 256, 64][B, HW, C]?

3, maybe naive, but those questions really confuse me, looking forward to your reply.

**Comment by fengzhang427** [comment]
The input shapes here are (H/P*W/P)*C/4, (H/2P*W/2P)*C/2, (H/4P*W/4P)*C/4, (16*16)*64 The 16 here means 64/4, that is, the patch size is 4, and then the patch size is increased in turn downwards. size, 8 means 64/8, 4 means 64/16.
You can refer to the NIPS 2021 paper "TransGAN: Two Pure Transformers Can Make OneStrong GAN, and That Can Scale Up" for the transformer architecture, which I also mentioned and cited in my paper, and the baseline structure of Fourier Transformer Discriminator is based on this paper.
